sudo: false
notifications:
  email:
    on_success: never
language: ruby
rvm:
  - 2.4.1
cache:
  directories:
    - vendor/bundle
before_install:
  - gem update --remote bundler
script:
  - bundle exec rubocop --display-cop-names
gemfile:
  - Gemfile
